from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from models.enums import SourceType, WorkplaceType, EmploymentType, MatchLevel


@dataclass
class JobSource:
    type: SourceType
    company_name: str
    company_name_cn: str
    source_url: str
    fetched_at: str = ""
    is_active: bool = True
    external_id: str = ""


@dataclass
class JobInfo:
    title: str
    title_cn: str = ""
    department: str = ""
    team: str = ""
    employment_type: EmploymentType = EmploymentType.UNSPECIFIED
    workplace_type: WorkplaceType = WorkplaceType.UNSPECIFIED
    seniority_level: str = ""


@dataclass
class JobLocation:
    city: str = ""
    province: str = ""
    country: str = ""
    is_remote_in_china: bool = False
    locations_text: str = ""


@dataclass
class JobContent:
    description_plain: str = ""
    description_html: str = ""
    responsibilities: list[str] = field(default_factory=list)
    qualifications: list[str] = field(default_factory=list)


@dataclass
class JobCompensation:
    salary_min: Optional[float] = None
    salary_max: Optional[float] = None
    salary_currency: str = ""
    salary_period: str = ""       # annual, monthly
    salary_description: str = ""


@dataclass
class JobDates:
    posted_on: str = ""
    closing_on: str = ""


@dataclass
class FilterResult:
    is_software_role: bool = False
    matched_keywords: list[str] = field(default_factory=list)
    match_score: float = 0.0
    match_level: MatchLevel = MatchLevel.NONE


@dataclass
class Job:
    id: str = ""                          # UUID generated by system
    source: JobSource = field(default_factory=JobSource)
    job: JobInfo = field(default_factory=JobInfo)
    location: JobLocation = field(default_factory=JobLocation)
    content: JobContent = field(default_factory=JobContent)
    compensation: JobCompensation = field(default_factory=JobCompensation)
    dates: JobDates = field(default_factory=JobDates)
    filter_result: FilterResult = field(default_factory=FilterResult)
    language: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "source": {
                "type": self.source.type.value,
                "company_name": self.source.company_name,
                "company_name_cn": self.source.company_name_cn,
                "source_url": self.source.source_url,
                "fetched_at": self.source.fetched_at,
                "is_active": self.source.is_active,
                "external_id": self.source.external_id,
            },
            "job": {
                "title": self.job.title,
                "title_cn": self.job.title_cn,
                "department": self.job.department,
                "team": self.job.team,
                "employment_type": self.job.employment_type.value,
                "workplace_type": self.job.workplace_type.value,
                "seniority_level": self.job.seniority_level,
            },
            "location": {
                "city": self.location.city,
                "province": self.location.province,
                "country": self.location.country,
                "is_remote_in_china": self.location.is_remote_in_china,
                "locations_text": self.location.locations_text,
            },
            "content": {
                "description_plain": self.content.description_plain,
                "description_html": self.content.description_html,
                "responsibilities": self.content.responsibilities,
                "qualifications": self.content.qualifications,
            },
            "compensation": {
                "salary_min": self.compensation.salary_min,
                "salary_max": self.compensation.salary_max,
                "salary_currency": self.compensation.salary_currency,
                "salary_period": self.compensation.salary_period,
                "salary_description": self.compensation.salary_description,
            },
            "dates": {
                "posted_on": self.dates.posted_on,
                "closing_on": self.dates.closing_on,
            },
            "filter_result": {
                "is_software_role": self.filter_result.is_software_role,
                "matched_keywords": self.filter_result.matched_keywords,
                "match_score": self.filter_result.match_score,
                "match_level": self.filter_result.match_level.value,
            },
            "language": self.language,
        }
